### Register a new resource
POST http://localhost:8081/api/v1/resources
Content-Type: application/json

{
  "type": "example_type",
  "cpu_cores": 4,
  "memory_mb": 8192,
  "storage_gb": 100
}

### Get all resources
GET http://localhost:8081/api/v1/resources

### Update a resource
PUT http://localhost:8081/api/v1/resources/64468d2410bc4dfaaad85429
Content-Type: application/json

{
  "type": "updated_type",
  "cpu_cores": 6,
  "memory_mb": 16384,
  "storage_gb": 200
}

### Delete a resource
DELETE http://localhost:8081/api/v1/resources/64468d2410bc4dfaaad85429

### Allocate a resource
POST http://localhost:8081/api/v1/allocations
Content-Type: application/json

{
  "borrower_id": "{{borrower_id}}",
  "resource_request": {
    "resource_type": "example_type",
    "min_cpu_cores": 2,
    "min_memory_mb": 4096,
    "min_storage_gb": 50
  }
}

### Release a resource
DELETE http://localhost:8081/api/v1/allocations/{{allocation_id}}

### Create borrower
POST http://localhost:8081/api/v1/borrowers
Content-Type: application/json

{
    "name": "example_type"
}
