###
### Register User
###

POST https://localhost:8443/register
Content-Type: application/json

{
  "username": "john_doe",
  "password": "secretpassword"
}


###
### Login User
###

POST https://localhost:8443/login
Content-Type: application/json

{
  "username": "john_doe",
  "password": "secretpassword"
}
