### Register a new resource
POST https://localhost:8440/api/v1/resources
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5fZG9lIn0.biDOjHSPxjIWUsmik0YpW-7SwXhT2g48F2UVVSrie4U

{
  "cpu_cores": 4,
  "memory_mb": 8192
}

### Get all resources
GET https://localhost:8440/api/v1/resources/free
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5fZG9lIn0.biDOjHSPxjIWUsmik0YpW-7SwXhT2g48F2UVVSrie4U


### Update a resource
PUT https://localhost:8440/api/v1/resources/64468d2410bc4dfaaad85429
Content-Type: application/json

{
  "cpu_cores": 6,
  "memory_mb": 16384
}

### Delete a resource
DELETE https://localhost:8440/api/v1/resources/64468d2410bc4dfaaad85429

### Allocate a resource
POST https://localhost:8440/api/v1/allocations
Content-Type: application/json

{
  "borrower_id": "6446df1322b3d57d49cc2264",
  "resource": {
    "cpu_cores": 4,
    "memory_mb": 8192
  }
}

### Release a resource
DELETE https://localhost:8440/api/v1/allocations/6447e82ed4e0efa0cf66a8ed

### Create borrower
POST https://localhost:8440/api/v1/borrowers
Content-Type: application/json

{
    "name": "default_borrower"
}

### Create lender
POST https://localhost:8440/api/v1/lenders
Content-Type: application/json

{
  "name": "default_lender"
}

